spec:
  template:
    spec:
      containers:
        - name: oauth2-proxy
          args:
            - --provider=github
            - --github-org=tzevet-ai
            - --http-address=0.0.0.0:4180
            - --upstream=http://filebrowser:8080/files/
            - --upstream=http://lidarr:8686/lidarr/
            - --upstream=http://qbittorrent:8080/qbt/
            - --upstream=http://prowlarr:9696/prowlarr/
            - --upstream=http://sonarr:8989/sonarr/
            - --upstream=http://music-downloader-frontend:8080/download/
            - --upstream=http://navidrome:4533
            - --email-domain=*
            - --cookie-secure=true
            - --redirect-url=https://navidrome.apps.okd.benrachmiel.org/oauth2/callback
            - --scope=user:email read:org
            - --skip-auth-route=GET=^/rest/.*
            - --skip-auth-route=POST=^/rest/.*
            - "--banner=<a href=\"/files/\">\U0001F4C1 Files</a> | <a href=\"/\">\U0001F3B5 Player</a> | <a href=\"/lidarr/\">\U0001F3B6 Lidarr</a> | <a href=\"/sonarr/\">\U0001F4FA Sonarr</a> | <a href=\"/qbt/\">\u2B07 qBittorrent</a> | <a href=\"/prowlarr/\">\U0001F50D Prowlarr</a> | <a href=\"https://jellyfin.apps.okd.benrachmiel.org\">\U0001F3AC Jellyfin</a> | <a href=\"/download/\">\U0001F4E5 Downloader</a>"
