apiVersion: batch/v1
kind: Job
metadata:
  generateName: toolbox-embed-lyrics-
  namespace: pedals
spec:
  template:
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: toolbox
          image: gitlab.benrachmiel.org:5050/bvf2104/music-downloader-from-csv/toolbox:latest
          args: ["tools.embed_lyrics", "/music"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: music
              mountPath: /music
      volumes:
        - name: music
          persistentVolumeClaim:
            claimName: preamp-music
      restartPolicy: Never
  backoffLimit: 1
