apiVersion: v1
kind: Service
metadata:
  name: {{ include "gain-downloader.fullname" . }}
  labels:
    {{- include "gain-downloader.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: oauth-proxy
      protocol: TCP
      name: http
  selector:
    {{- include "gain-downloader.selectorLabels" . | nindent 4 }}
